name: fgl-iso
version: '0.1.0.0'
category: Data Structures, Graphs
author: Ignat Insarov
maintainer: kindaro@gmail.com
copyright: 2017 Ignat Insarov
license: ISC
github: kindaro/fgl-iso
synopsis: Graph isomorphism & canonicalization.
description: Graph isomorphism & canonicalization.
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Graph.Inductive.Isomorphism
  dependencies:
  - base >=4.7 && <5
  - fgl
# executables:
#   fgl-iso-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - base
#     - fgl-iso
# tests:
#   fgl-iso-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - base
#     - fgl-iso
